### ISSUE TITLE
Please clarify the code license

### ISSUE THREAD

**Issue by johnl** [casimir/xdg-go#1]
can you clarify what the license of the code is? If you could provide a copy of the license in a file called LICENSE, that'd be great. You should ideally add it and a copyright notice to each file too :)

Thanks!

**Comment by casimir** [comment]
Here you go. I wrote a quick documentation too (should have done it long ago). Happy to see personal hacks can serve others.

**Comment by johnl** [comment]
Nice one, thanks Martin!
